services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment: # variáveis de ambiente
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
  rabbitmq:
    image: rabbitmq:3.13-management # versão que tem um painel administrativo
    ports:
      - 15672:15672 # porta do painel administrativo rabbitMQ
      - 5672:5672 # porta principal



